---
services:

  leader:
    build:
      context: leader-app
    stop_signal: SIGINT
    restart: always
    volumes:
      - /var/beast:/var/beast
    environment:
      - FLASK_DATABASE_PATH=${FLASK_DATABASE_PATH}
    ports:
      - '5000:5000'

  frontend:
    build:
      context: leader-app-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_BASE_URL=http://127.0.0.1:5000
    ports:
      - '3000:3000'

  # Disable the Button Game for the time being...
  # button:
  #   build:
  #     context: the-button
  #   stop_signal: SIGINT
  #   restart: always
  #   ports:
  #     - '5005:5000'
