---
services:

  leader:
    build:
      context: leader-app
    stop_signal: SIGINT
    ports:
      - '5000:5000'

  button:
    build:
      context: button
    stop_signal: SIGINT
    ports:
      - '5005:5000'
