---
- name: Farming is fun!
  hosts: farmer
  gather_facts: true
  become: true

  vars:
    run_upgrades: false
    running_app: leader-app

    pip_install_packages:
      - name: docker
    docker_install_compose: false
    docker_install_compose_plugin: true
    docker_users:
      - "{{ ansible_user }}"

  pre_tasks:
    - name: Upgrade everything on initial provision.
      ansible.builtin.include_tasks: tasks/upgrade.yml
      when: run_upgrades

  roles:
    - name: geerlingguy.pip
    - name: geerlingguy.docker

  tasks:
    - name: Copy apps to the server.
      ansible.builtin.copy:
        src: ../{{ item }}/
        dest: /opt/{{ item }}/
      with_items:
        - leader-app
        - the-button
      tags: ['app']

    - name: Ensure the leader-app is running if configured.
      community.docker.docker_compose:
        project_src: /opt/leader-app
        state: present
        stopped: {{ true if running_app == 'leader-app' else false }}
      tags: ['app']

    - name: Ensure the app that's not running is stopped.
      community.docker.docker-compose:
        project_src: /opt/the-button
        state: present
        stopped: {{ true if running_app == 'the-button' else false }}
      tags: ['app']
