---
- name: Farming is fun!
  hosts: farmer
  gather_facts: true
  become: true

  vars:
    run_upgrades: false
    github_access_token: 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

    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_install_compose: true
    docker_compose_version: "1.29.2"
    docker_install_compose_plugin: false
    docker_users:
      - "{{ ansible_user }}"

  pre_tasks:
    - name: Update apt caches if required.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade everything on initial provision.
      ansible.builtin.include_tasks: tasks/upgrade.yml
      when: run_upgrades

  roles:
    - name: geerlingguy.pip
    - name: geerlingguy.docker

  tasks:
    - name: Clone project to the server.
      ansible.builtin.git:
        repo: "https://geerlingguy:{{ github_access_token | urlencode }}@github.com/geerlingguy/beast-game.git"
        dest: /opt/beast-game
      tags: ['app']

    - name: Ensure the Docker environment is running.
      community.docker.docker_compose:
        project_src: /opt/beast-game
        state: present
      tags: ['app']
