---
- name: Someone set us up the Potatoes
  hosts: potatoes
  gather_facts: true
  become: true

  vars:
    run_upgrades: false
    server_url: "http://10.0.100.15:5000"

  handlers:
    - name: restart apps
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - light-control
        - button-monitor

  pre_tasks:
    - name: Upgrade everything on initial provision.
      ansible.builtin.include_tasks: tasks/upgrade.yml
      when: run_upgrades

  tasks:
    - name: Configure admin user and sudoers.
      ansible.builtin.include_tasks: tasks/admin-user.yml
      tags: ['user']

    - name: Install required packages.
      ansible.builtin.package:
        name:
          - gpiod
          - python3-libgpiod
          - python3-smbus
          - python3-pip
        state: present

    - name: Install required pip packages.
      ansible.builtin.pip:
        name:
          - requests
          - pyyaml
        state: present

    - name: Configure I2C overlay on Armbian.
      ansible.builtin.include_tasks: tasks/i2c.yml

    - name: Configure the room-app scripts.
      ansible.builtin.include_tasks: tasks/room-app.yml
      tags: ['app']
